services:
  app:
    build: .
    ports:
      - 8080:8080
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090
    restart: unless-stopped
    volumes:
      - ./contrib/prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./contrib/grafana:/etc/grafana/provisioning/datasources
